### ISSUE TITLE
openAI api key not free

### ISSUE THREAD

**Issue by aditya-8-88** [Aryansrivastava07/QuizzCraft#1]
why not shift to gemini or some other free api key provider

**Comment by Aryansrivastava07** [comment]
The project has been migrated to gemini .Thanks for your concern.

**Comment by Aryansrivastava07** [comment]
The project has been migrated to gemini .Thanks for your concern.

**Comment by Aryansrivastava07** [comment]
The project has been migrated to gemini .Thanks for your concern.
